//
//  CameraViewController.m
//  CupixMADV360Demo
//
//  Created by QiuDong on 2018/6/26.
//  Copyright © 2018年 QiuDong. All rights reserved.
//

#import "CameraViewController.h"
#import "MVGLView_ExternC.h"
#import "MadvGLRenderer.h"
#import "MVCameraClient.h"
#import "MVMedia.h"
#import "Utils/UIView+HierachyExtensions.h"
#import "MVMediaManager.h"
#import "MadvGLRenderer_iOS.h"
#import "EXIFParser.h"
#import "MadvUtils.h"
#import <iostream>

@interface CameraViewController () <MVCameraClientObserver, MVMediaDataSourceObserver, MVMediaDownloadStatusObserver>

@property (nonatomic, weak) IBOutlet UIButton* connectButton;
@property (nonatomic, weak) IBOutlet UIButton* shootButton;

@property (nonatomic, strong) MVCameraDevice* device;

-(IBAction)onConnectButtonClicked:(id)sender;
-(IBAction)onShootButtonClicked:(id)sender;

@end

@implementation CameraViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    /*
    MVGLView* glView = [[MVGLView alloc] initWithFrame:self.view.bounds lutPath:nil lutSrcSizeL:CGSizeMake(DEFAULT_LUT_VALUE_WIDTH, DEFAULT_LUT_VALUE_HEIGHT) lutSrcSizeR:CGSizeMake(DEFAULT_LUT_VALUE_WIDTH, DEFAULT_LUT_VALUE_HEIGHT) outputVideoBaseName:nil encoderQualityLevel:MVQualityLevelOther forCapturing:NO];
    self.glView = glView;
    [self.view addSubview:glView];
    
    NSString* testJpegPath = [[NSBundle mainBundle] pathForResource:@"test" ofType:@"jpg"];
    [self.glView.glRenderLoop drawJPEG:testJpegPath];
    [self.glView.glRenderLoop setPanoramaMode:PanoramaDisplayModeStereoGraphic];
    //*/
}

-(void) viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [[MVCameraClient sharedInstance] addObserver:self];//#MADVSDK#
    // #MADVSDK#
    MVMediaManager* mediaManager = [MVMediaManager sharedInstance];
    mediaManager.downloadMediasIntoDocuments = YES;// :Important
    mediaManager.noStitchingAfterPhotoDownloaded = YES;// :Important to Cupix
    // Add as observer for media manager:
    [mediaManager addMediaDataSourceObserver:self];
    [mediaManager addMediaDownloadStatusObserver:self];
}

-(void) viewWillDisappear:(BOOL)animated {
    [[MVCameraClient sharedInstance] removeObserver:self];//#MADVSDK#
    MVMediaManager* mediaManager = [MVMediaManager sharedInstance];
    [mediaManager removeMediaDataSourceObserver:self];
    [mediaManager removeMediaDownloadStatusObserver:self];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma mark UIEvents
-(IBAction)onConnectButtonClicked:(id)sender {
    if (0 == self.connectButton.tag)
    {
        self.connectButton.enabled = NO;
        [self.connectButton setTitle:@"Connecting..." forState:UIControlStateNormal];
        [[MVCameraClient sharedInstance] connectCamera];//#MADVSDK#
    }
    else if (1 == self.connectButton.tag)
    {
        self.connectButton.enabled = NO;
        [self.connectButton setTitle:@"Disconnecting..." forState:UIControlStateNormal];
        [[MVCameraClient sharedInstance] disconnectCamera];//#MADVSDK#
    }
}

-(IBAction)onShootButtonClicked:(id)sender {
    [[MVCameraClient sharedInstance] startShooting];//#MADVSDK#
    self.shootButton.enabled = NO;
    [self.shootButton setTitle:@"Shooting..." forState:UIControlStateNormal];
}

#pragma mark MVCameraClientObserver

-(void) didConnectSuccess:(MVCameraDevice *)device {
    [self setContentPath:@"rtsp://192.168.42.1/live" parameters:nil];//#MADVSDK#
    self.connectButton.tag = 1;
    self.connectButton.enabled = YES;
    [self.connectButton setTitle:@"Disconnect" forState:UIControlStateNormal];
    self.shootButton.hidden = NO;
}

-(void) didConnectFail:(NSString *)errorMessage {
    [self didDisconnect:CameraDisconnectReasonUnknown];
}

-(void) didDisconnect:(CameraDisconnectReason)reason {
    self.connectButton.tag = 0;
    self.connectButton.enabled = YES;
    [self.connectButton setTitle:@"Connect" forState:UIControlStateNormal];
    self.shootButton.hidden = YES;
}

-(void) didCameraModeChange:(CameraMode)mode subMode:(CameraSubMode)subMode param:(NSInteger)param {
    if (mode != CameraModePhoto || subMode != CameraSubmodePhotoNormal)
    {
        //#MADVSDK# Change to Normal Photo Shooting mode if the camera is not at it:
        [[MVCameraClient sharedInstance] setCameraMode:CameraModePhoto subMode:CameraSubmodePhotoNormal param:0];
    }
}

-(void) didEndShooting:(NSString *)remoteFilePath videoDurationMills:(NSInteger)videoDurationMills error:(int)error errMsg:(NSString *)errMsg {
    self.shootButton.enabled = YES;
    [self.shootButton setTitle:@"Shoot" forState:UIControlStateNormal];
}

#pragma mark    MVMediaDataSourceObserver

-(void)didCameraMediasReloaded:(NSArray<MVMedia *> *) medias dataSetEvent:(DataSetEvent)dataSetEvent errorCode:(int)errorCode {
    if (dataSetEvent == DataSetEventAddNew)
    {// As new picture file(s) generated by the camera, immediately start downloading:
        NSLog(@"addDownloadingOfMedias : %@", medias);
        [[MVMediaManager sharedInstance] addDownloadingOfMedias:@[medias[0]] completion:^{
            NSLog(@"#MADVSDK# didCameraMediasReloaded : Batch downloading started");
        } progressBlock:^(int completedCount, int totalCount, BOOL *cancel) {
            NSLog(@"#MADVSDK# didCameraMediasReloaded : Batch downloading progress : %d/%d", completedCount, totalCount);
        }];
    }
}

-(void) didLocalMediasReloaded:(NSArray<MVMedia *> *) medias dataSetEvent:(DataSetEvent)dataSetEvent {
    
}

-(void)didFetchThumbnailImage:(UIImage *)image ofMedia:(MVMedia*)media error:(int)error {
    
}

-(void)didFetchMediaInfo:(MVMedia *)media error:(int)error {
    
}

- (void) didFetchRecentMediaThumbnail:(MVMedia*)media image:(UIImage*)image error:(int)error {
    
}

#pragma mark    MVMediaDownloadStatusObserver

- (void) didDownloadStatusChange:(int)downloadStatus errorCode:(int)errorCode ofMedia:(MVMedia*)media {
    if (!errorCode && downloadStatus == MVMediaDownloadStatusFinished)
    {// When a media file has been successfully downloaded, get its local file name(relative to sandbox document directory) from this callback
        //To download files into sandbox from camera, "Application supports iTunes file sharing" and "App Transport Security Settings"->"Allow Arbitrary Loads" in Info.plist should all be set to YES
        NSLog(@"#MADVSDK# didDownloadStatusChange : Media dowloading finished, stitched is '%@', original is '%@'", media.localPath, [MVPanoRenderer preStitchPictureFileName:media.cameraUUID fileName:media.localPath]);
        if (![media.localPath.pathExtension.lowercaseString isEqualToString:@"jpg"]) return;
        
        NSString* documentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0];
        NSString *sourcePath, *destPath;
        MVMediaManager* mediaManager = [MVMediaManager sharedInstance];
        if (mediaManager.noStitchingAfterPhotoDownloaded)
        {
            sourcePath = [[[documentPath stringByAppendingPathComponent:media.localPath] stringByAppendingPathExtension:media.cameraUUID] stringByAppendingPathExtension:@"prestitch.jpg"];
            destPath = [[documentPath stringByAppendingPathComponent:media.localPath] stringByAppendingPathExtension:@"stitched.jpg"];
        }
        else
        {
            sourcePath = [documentPath stringByAppendingPathComponent:media.localPath];
            destPath = [sourcePath stringByAppendingPathExtension:@"stitched.jpg"];
        }
        NSString* tempLUTDirectory = makeTempLUTDirectory(sourcePath);
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            renderMadvJPEGToJPEG(destPath, sourcePath, tempLUTDirectory, 0, 0, false);
            [[NSFileManager defaultManager] removeItemAtPath:sourcePath error:nil];
        });
    }
}

- (void) didDownloadProgressChange:(NSInteger)downloadedBytes totalBytes:(NSInteger)totalBytes ofMedia:(MVMedia*)media {
    NSLog(@"#MADVSDK# didDownloadProgressChange : Media(%@) dowloading progress %.2f%%", media.localPath, 100.f*downloadedBytes/totalBytes);
}

- (void) didBatchDownloadStatusChange:(int)downloadStatus ofMedias:(NSArray<MVMedia *>*)medias {
    
}

- (void) didDownloadingsHung {
    
}

- (void) didReceiveStorageWarning {
    
}

#pragma mark    MVKxMovieViewController Callbacks

- (void) didSetupPresentView:(UIView*)newGLView {
    //#MADVSDK# Find the glView in view hierachy and bring it to back, in order to avoid occlusion:
    __block MVGLView* presentView = nil;
    [self.view traverseMeAndSubviews:^(UIView* view) {
        if ([view isKindOfClass:MVGLView.class])
        {
            presentView = (MVGLView*)view;
        }
    }];
    if (!presentView)
    {
        presentView = (MVGLView*)newGLView;
        [self.view addSubview:presentView];
    }
    [self.view sendSubviewToBack:presentView];
    
    presentView.contentMode = UIViewContentModeScaleAspectFit;
    presentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleBottomMargin;
}

@end
